(define (port-copy iport oport)
  (define (iter c)
    (unless (eof-object? c)
      (write-char c oport)
      (iter (read-char iport))))
  (iter (read-char iport)))

(define (file-copy src dst)
  (let ((iport (open-input-file src))
        (oport (open-output-file dst)))
    (port-copy iport oport)
    (close-input-port iport)
    (close-output-port oport)))


(when (<= (length (command-line)) 2)
  (display "usage: copy <src> <dst>")
  (newline)
  (exit 1))
(let ((src (list-ref (command-line) 1))
      (dst (list-ref (command-line) 2)))
  (file-copy src dst))
