/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lib_TestLibrary */

#ifndef _Included_lib_TestLibrary
#define _Included_lib_TestLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lib_TestLibrary
 * Method:    println
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_lib_TestLibrary_println
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
